backend:
  name: github
  repo: inlokjabli/loker-jawabali
  branch: main

media_folder: "gambar"
public_folder: "/gambar"

collections:
  - name: "lowongan"
    label: "Lowongan"
    folder: "lowongan"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Isi", name: "body", widget: "markdown" }
